#pragma once

#undef DEBOUNCE
#define DEBOUNCE 5

#define TAPPING_TERM 180
#define TAPPING_TERM_PER_KEY
#define QUICK_TAP_TERM 0
#define QUICK_TAP_TERM_PER_KEY
#define FLOW_TAP_TERM 150
#define CHORDAL_HOLD
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "zPzB4/ZPDMzV"
#define LAYER_STATE_8BIT
